---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "knowledgebase-slackbot.embedding-pvc" . }}
  labels:
    app: knowledgebase
    component: embedding
    {{- if .Values.embeddingPVC.labels }}
    {{- toYaml .Values.embeddingPVC.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.embeddingPVC.annotations }}
  annotations: {{- toYaml .Values.embeddingPVC.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.embeddingPVC.storageClassName }}
  storageClassName: {{ .Values.embeddingPVC.storageClassName }}
  {{- end }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.embeddingPVC.size }}
