apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "knowledgebase-slackbot.helm-hooks-serviceaccount-name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "knowledgebase-slackbot.helm-hooks-role-name" . }}
rules:
- apiGroups:
  - "apps"
  resources:
  - statefulsets
  verbs:
  - get
  - patch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "knowledgebase-slackbot.helm-hooks-rolebinding-name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "knowledgebase-slackbot.helm-hooks-role-name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "knowledgebase-slackbot.helm-hooks-serviceaccount-name" . }}
  namespace: {{ .Release.Namespace }}
