apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "knowledgebase-slackbot.ingest" . }}
  labels:
    app: knowledgebase
    component: ingest
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "2"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
{{ include "knowledgebase-slackbot.ingest-job-spec" . }}
