apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kibana
  labels:
    app: knowledgebase
    component: kibana
    paas.redhat.com/appcode: CMPA-001
  annotations:
    kubernetes.io/reclaimPolicy: Delete
spec:
  storageClassName: aws-ebs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
