apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "knowledgebase-slackbot.logs-pvc" . }}
  labels:
    app: knowledgebase
    component: slackbot
    paas.redhat.com/appcode: CMPA-001
  annotations:
    kubernetes.io/reclaimPolicy: Delete
spec:
  storageClassName: aws-efs-tier-c4
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.logsVolumeSize }}
