apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knowledgebase-slackbot.openai-secret" . }}
type: Opaque
data:
  api_key: {{ (required "OpenAI Token must be set" .Values.openaiToken) | b64enc }}
