apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "knowledgebase-slackbot.redis-pvc-name" . }}
  labels:
    app: knowledgebase
    component: redis
    {{- if .Values.redisPVC.labels }}
    {{- toYaml .Values.redisPVC.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.redisPVC.annotations }}
  annotations: {{- toYaml .Values.redisPVC.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.redisPVC.storageClassName }}
  storageClassName: {{ .Values.redisPVC.storageClassName }}
  {{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redisPVC.size | quote }}
