apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "knowledgebase-slackbot.redis-pvc-name" . }}
  labels:
    app: knowledgebase
    component: redis
    paas.redhat.com/appcode: CMPA-001
  annotations:
    kubernetes.io/reclaimPolicy: Delete
spec:
  storageClassName: aws-ebs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
