apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knowledgebase-slackbot.slackbot-pod-name" . }}
  labels:
    app: knowledgebase
    component: slackbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knowledgebase
      component: slackbot
  template:
    metadata:
      annotations:
        checksum/knowledgebase-config: {{ include (print $.Template.BasePath "/knowledgebase-configmap.yaml") . | sha256sum }}
        checksum/fluent-bit-config: {{ include (print $.Template.BasePath "/fluent-bit-configmap.yaml") . | sha256sum }}
        checksum/slack-tokens: {{ include (print $.Template.BasePath "/slackbot-tokens-secret.yaml") . | sha256sum }}
        checksum/slack-forward-channel: {{ include (print $.Template.BasePath "/forward-channel-secret.yaml") . | sha256sum }}
      labels:
        app: knowledgebase
        component: slackbot
    spec:
      containers:
      - name: slackbot
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["python", "-m", "knowledge_base_gpt.apps.slackbot"]
        volumeMounts:
        - mountPath: "/db"
          name: embedding
          readOnly: true
        - mountPath: /logs
          name: logs
        - mountPath: /etc/knowledgebase
          name: knowledgebase-config
        - mountPath: /.cache
          name: cache
        env:
        - name: KNOWLEDGE_BASE_SETTINGS_FOLDER
          value: /etc/knowledgebase
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ include "knowledgebase-slackbot.redis-password-secret" . }}"
              key: redis-password
        - name: FORWARD_QUESTION_CHANNEL_NAME
          valueFrom:
            secretKeyRef:
              name: "{{ include "knowledgebase-slackbot.forward-channel-secret" . }}"
              key: channel
        - name: SLACK_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: "{{ include "knowledgebase-slackbot.slackbot-tokens-secret" . }}"
              key: app-token
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: "{{ include "knowledgebase-slackbot.slackbot-tokens-secret" . }}"
              key: bot-token
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ include "knowledgebase-slackbot.openai-secret" . }}"
              key: api_key
        resources:
          limits:
            cpu: 1
            memory: 1Gi
      - name: fluent-bit
        image: "docker.io/fluent/fluent-bit:{{ .Values.fluentbitImageTag }}"
        command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit-config/fluent-bit.conf"]
        volumeMounts:
        - mountPath: /logs
          name: logs
        - name: fluent-bit-config
          mountPath: /fluent-bit-config
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
      - name: logrotate
        image: "ghcr.io/ygalblum/logrotate-sidecar:{{ .Values.logrotate.imageTag }}"
        volumeMounts:
        - mountPath: /logs
          name: logs
        env:
        - name: LOGS_DIRECTORIES
          value: /logs
        - name: LOGROTATE_SIZE
          value: {{ .Values.logrotate.size | quote }}
        - name: LOGROTATE_COMPRESSION
          value: compress
        - name: LOGROTATE_INTERVAL
          value: {{ .Values.logrotate.interval | quote }}
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: knowledgebase-config
        configMap:
          name: {{ include "knowledgebase-slackbot.knowledgebase-configmap" . }}
      - name: embedding
        persistentVolumeClaim:
          claimName: {{ include "knowledgebase-slackbot.embedding-pvc" . }}
      - name: logs
        persistentVolumeClaim:
          claimName: {{ include "knowledgebase-slackbot.logs-pvc" . }}
      - name: cache
        emptyDir:
          sizeLimit: 1Gi
      - name: fluent-bit-config
        configMap:
          name: {{ include "knowledgebase-slackbot.fluent-bit-config" . }}
