apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knowledgebase-slackbot.vault-agent-config-configmap" . }}
data:
  vault.hcl: |-
{{ include "knowledgebase-slackbot.vault-agent-config" . | indent 4 }}
