---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "knowledgebase-slackbot.vllm-pvc" . }}
  labels:
    app: vllm
    {{- if .Values.vllm.pvc.labels }}
    {{- toYaml .Values.vllm.pvc.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.vllm.pvc.annotations }}
  annotations: {{- toYaml .Values.vllm.pvc.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.vllm.pvc.storageClassName }}
  storageClassName: {{ .Values.vllm.pvc.storageClassName }}
  {{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.vllm.pvc.size | quote }}
