slackbot:
  app_token: $SLACK_APP_TOKEN|""
  bot_token: $SLACK_BOT_TOKEN|""
  forward_channel: $FORWARD_QUESTION_CHANNEL_NAME|""

llm:
  mode: ollama

ollama:
  llm_model: $MODEL|mistral
  embedding_model: $EMBEDDINGS_MODEL_NAME|nomic-embed-text

history: {}

redis:
  host: $REDIS_HOST|localhost
  password: $REDIS_PASSWORD|""

log: {}

content_loader: {}

google_drive:
  service_key_file: $SERVICE_KEY_FILE|""
  folder_id: $GOOGLE_DRIVE_FOLDER_ID|""

text_splitter: {}

embedding:
  mode: ollama

hugging_face:
  embedding_model: $EMBEDDINGS_MODEL_NAME|all-MiniLM-L6-v2

vectorstore: {}