# Default values for knowledgebase-slackbot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/yblum/knowledge_base_gpt
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Certificate Parameters
certificateIssuer: ""
certificateDNSNames:
- slackbot.knowledgebase
certificateDuration: 87600h

# Embedding Volume Parameters
embeddingVolumeSize: 2Gi

# Google Folder ID to ingest
ingestFolderID: ""

# Metrics Volume Parameters
logsVolumeSize: 1Gi

# Address for Ollama Secure Service
ollamaServerAddress: ""
ollamaServerSecurePort: 11435

ollamaChatModel: mistral
ollamaEmbeddingModel: nomic-embed-text

# Slack Channel to forward unanswered conversations
forwardChannel: ""

# Slack App and Bot tokens
slackAppToken: ""
slackBotToken: ""

envoyProxyImageTag: v1.29-latest
fluentbitImageTag: "2.2"

logrotate:
  imageTag: latest
  size: 1M
  interval: hourly

ollamaServerAdminSecurePort: 19901
ollamaServerFluentBitSecurePort: 12021

redis:
  architecture: standalone

elasticsearch:
  master:
    masterOnly: false
    replicaCount: 1
    resources:
      limits:
        memory: "4Gi"
    heapSize: 2G
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0
  global:
    kibanaEnabled: true
  sysctlImage:
    enabled: false
