---
name: Release

on:
  release:
    types:
      - published

jobs:
  helmlint:
    uses: ygalblum/knowledge-base-gpt/.github/workflows/helmlint.yml@main
  pylint:
    uses: ygalblum/knowledge-base-gpt/.github/workflows/pylint.yml@main
  pycodestyle:
    uses: ygalblum/knowledge-base-gpt/.github/workflows/pycodestyle.yml@main
  # codespell:
  #   uses: ygalblum/knowledge-base-gpt/.github/workflows/codespell.yml@main
  prechecks:
    needs:
      - helmlint
      - pylint
      - pycodestyle
      # - codespell
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.helmlint.result }}',
          '${{ needs.pylint.result }}',
          '${{ needs.pycodestyle.result }}',
          ]) == {'success'}"
  release:
    needs:
      - prechecks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: knowledge_base_gpt
          tags: latest ${{ github.sha }} ${{ github.ref_name }}
          containerfiles: |
            ./Containerfile

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/yblum
          username: yblum+knowledge_base_gpt
          password: ${{ secrets.QUAY_REGISTRY_PASSWORD }}

  update-helm:
    needs:
      - release
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible
        run: pip install --upgrade ansible-core antsibull-changelog

      - name: Update appVersion in the Helm Chart
        run: sed -i 's/appVersion:.*$/appVersion:{{:dumb_space_issue:}}${{ github.ref_name }}/' cloud/helm/knowledgebase-slackbot/Chart.yaml; sed -i 's/{{:dumb_space_issue:}}/ /' cloud/helm/knowledgebase-slackbot/Chart.yaml

      - name: Create Pull Request
        id: prcreate
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update Helm Chart to use appVersion ${{ github.ref_name }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          base: main
          branch: changelog-patches
          delete-branch: true
          title: '[RELEASE] Update Helm Chart to use appVersion ${{ github.ref_name }}'
          body: |
            Update Helm Chart to use appVersion
            - Update Helm Chart to use appVersion ${{ github.ref_name }}
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            changelog
            automated pr
          draft: false
...
